LootJS.modifiers(event => {
  // Every chest loot table used by the Ancient Temple.
  const templeTables = [
    'deeperdarker:chests/ancient_temple_apex',
    'deeperdarker:chests/ancient_temple_basement',
    'deeperdarker:chests/ancient_temple_fountain',
    'deeperdarker:chests/ancient_temple_secret',
    'deeperdarker:chests/ancient_temple_storage'
  ]
  const luna = [
    'ad_astra:chests/dungeon/moon/dungeon_chest',
    'ad_astra:chests/dungeon/moon/large_dungeon_chest',
    'ad_astra:chests/village/moon/house',
    'ad_astra_more_structures:chest/common_moon'
  ]
  event
    .addLootTableModifier(luna)
    .replaceLoot('minecraft:book', Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:lunar"}'))
    .replaceLoot('minecraft:ice', 'ad_astra:glacian_leaves')

  event
    .addLootTableModifier('ad_astra:corrupted_lunarian')
    .addLoot('ad_astra:raw_desh')
  // samples loot table
  // Give every Ancient Temple chest a 20% chance to contain one Netherite Scrap. 
//  templeTables.forEach(table => {
//    event
//      .addLootTableModifier(table)
//      .randomChance(0.20)
//      .addLoot(Item.of('minecraft:netherite_scrap'))
//  })

  // EXAMPLE 2:
  // Replace items generated by the storage table with something else.
  //
  // The final `true` preserves the original stack count. For example,
  // a generated stack of three diamonds becomes three emeralds.
  //LootJS.modifiers((event) => {
    // event.addBlockLootModifier("minecraft:gravel").replaceLoot("minecraft:flint", "minecraft:diamond");
    // or .replaceLoot("minecraft:flint", "minecraft:diamond", true) if you want to preserve the stack size
//});
  templeTables.forEach(table => {
    event
      .addLootTableModifier(table)
      .addLoot(Item.of('kubejs:star_remains'))
  })
  
})
  // sample for removing from loot table
//  event
//    .addLootTableModifier(
//      'deeperdarker:chests/ancient_temple_apex'
//    )
//    .removeLoot('minecraft:enchanted_golden_apple')
// )}