LootJS.modifiers(event => {
  // Every chest loot table used by the Ancient Temple.
  const templeTables = [
    'deeperdarker:chests/ancient_temple_apex',
    'deeperdarker:chests/ancient_temple_basement',
    'deeperdarker:chests/ancient_temple_fountain',
    'deeperdarker:chests/ancient_temple_secret',
    'deeperdarker:chests/ancient_temple_storage'
  ]
  const luna = [
    'ad_astra:chests/dungeon/moon/dungeon_chest',
    'ad_astra:chests/dungeon/moon/large_dungeon_chest',
    'ad_astra:chests/village/moon/house',
    'ad_astra_more_structures:chest/common_moon'
  ]
  event
    .addLootTableModifier(luna)
    .replaceLoot('minecraft:book', Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:lunar"}'))
    .replaceLoot('minecraft:ice', 'ad_astra:glacian_leaves')

  event
    .addEntityLootModifier('ad_astra:corrupted_lunarian')
    .addLoot('ad_astra:raw_desh')

  event
    .addLootTableModifier('minecraft:chests/nether_bridge')
    .addLoot(Item.of('minecraft:written_book', '{author:"Fallen One",pages:[\'{"text":"So you came to ask?\\\\n\\\\nJust, was the entity, however most do not fall the same as I do.\\\\n\\\\nTheir innerselves inverted, all devoured by a sin.\\\\n\\\\nThe most notable are those pig like things around. Gold, apparently catches their eyes.\\\\n"}\',\'{"text":"Greed. That was what they became. You have saw Heaven itself, so it might be hard to believe how those creatures fallen this low.\\\\n\\\\nThey used to make ingots of gold, and decorate around the place.\\\\n\\\\n"}\',\'{"text":"A Star was used in the final battle. I think you should have seen it by now, a tainted, corrupted remains of the former glory.\\\\n\\\\nThe humans of that time no longer live on earth, last I know, a tree on Luna was the place they travelled to."}\'],title:"Tales of Fallen"}'))
  // samples loot table
  // Give every Ancient Temple chest a 20% chance to contain one Netherite Scrap. 
//  templeTables.forEach(table => {
//    event
//      .addLootTableModifier(table)
//      .randomChance(0.20)
//      .addLoot(Item.of('minecraft:netherite_scrap'))
//  })
  event
    .addLootTableModifier('ad_astra_more_structures:chests/rare_other')
    .addLoot(Item.of('minecraft:paper', "{RepairCost:0,display:{Name:'{\"text\":\"A memory of Him\"}'}}"))
    .addLoot(Item.of('minecraft:paper', "{RepairCost:0,display:{Name:'{\"text\":\"May His Eye shines again\"}'}}"))
    .addLoot(Item.of('minecraft:paper', "{RepairCost:0,display:{Name:'{\"text\":\"And unfreeze our Lands\"}'}}"))
    .addLoot('astral_dimension:astral_eye')
  // EXAMPLE 2:
  // Replace items generated by the storage table with something else.
  //
  // The final `true` preserves the original stack count. For example,
  // a generated stack of three diamonds becomes three emeralds.
  //LootJS.modifiers((event) => {
    // event.addBlockLootModifier("minecraft:gravel").replaceLoot("minecraft:flint", "minecraft:diamond");
    // or .replaceLoot("minecraft:flint", "minecraft:diamond", true) if you want to preserve the stack size
//});
  templeTables.forEach(table => {
    event
      .addLootTableModifier(table)
      .addLoot(Item.of('kubejs:star_remains'))
  })
  event
    .addLootTableModifier('minecraft:chests/end_city_treasure').removeLoot('bedrockminer:bedrock_chunk')
  event
    .addLootTableModifier('minecraft:chests/bastion_treasure').removeLoot('bedrockminer:bedrock_chunk')
  event
    .addLootTableModifier('minecraft:chests/stronghold_crossing').removeLoot('bedrockminer:bedrock_chunk')
  event
    .addLootTableModifier('minecraft:chests/woodland_mansion').removeLoot('minecraft:creaking_heart')
  event
    .addLootTableModifier('minecraft:chests/woodland_mansion').removeLoot('minecraft:resin_chunk')
});

  // sample for removing from loot table
//  event
//    .addLootTableModifier(
//      'deeperdarker:chests/ancient_temple_apex'
//    )
//    .removeLoot('minecraft:enchanted_golden_apple')
// )}