// Generated 1.20.1 Forge recipes. Each base singularity is consumed exactly once.
ServerEvents.recipes(event => {
  event.remove({ id: 'extendedcrafting:ultimate_singularity' });

  const singularityIngredient = id => ({
    type: 'forge:nbt',
    item: 'extendedcrafting:singularity',
    nbt: `{Id:"extendedcrafting:${id}"}`
  });

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('actinium'),
      singularityIngredient('aluminium'),
      singularityIngredient('aluminum'),
      singularityIngredient('aluminum_alloy'),
      singularityIngredient('amber'),
      singularityIngredient('americium'),
      singularityIngredient('amethyst'),
      singularityIngredient('amethyst_bronze'),
      singularityIngredient('ancient_metal'),
      singularityIngredient('anti_neutronium'),
      singularityIngredient('antimony'),
      singularityIngredient('apalachia'),
      singularityIngredient('apalachia_chunk'),
      singularityIngredient('apatite'),
      singularityIngredient('aquatic'),
      singularityIngredient('arcanium'),
      singularityIngredient('arlemite'),
      singularityIngredient('astranite'),
      singularityIngredient('auraquartz'),
      singularityIngredient('awakened_supremium'),
      singularityIngredient('azurite'),
      singularityIngredient('baratol'),
      singularityIngredient('barium'),
      singularityIngredient('baronyte'),
      singularityIngredient('basalz_signalum'),
      singularityIngredient('beryllium'),
      singularityIngredient('bismuth'),
      singularityIngredient('black_iron'),
      singularityIngredient('black_quartz'),
      singularityIngredient('black_steel'),
      singularityIngredient('black_tungsten_alloy'),
      singularityIngredient('blaze_netherite'),
      singularityIngredient('blazing_quartz'),
      singularityIngredient('blazium'),
      singularityIngredient('blitz_lumium'),
      singularityIngredient('blizz_enderium'),
      singularityIngredient('bloodgem'),
      singularityIngredient('bloodstone'),
      singularityIngredient('boron'),
      singularityIngredient('boron_arsenide'),
      singularityIngredient('boron_nitride'),
      singularityIngredient('brass'),
      singularityIngredient('brick'),
      singularityIngredient('bronze'),
      singularityIngredient('cadmium'),
      singularityIngredient('calcium'),
      singularityIngredient('calorite'),
      singularityIngredient('carbon_manganese'),
      singularityIngredient('carminite'),
      singularityIngredient('carobbiite'),
      singularityIngredient('cerium'),
    ],
    result: { item: 'kubejs:compressed_singularity_alpha' }
  }).id('kubejs:compressed_singularity_alpha');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('certus_quartz'),
      singularityIngredient('cesium'),
      singularityIngredient('charged_ender'),
      singularityIngredient('chromium'),
      singularityIngredient('cinderslime'),
      singularityIngredient('cinnabar'),
      singularityIngredient('citrine'),
      singularityIngredient('cluster_of_brilliance'),
      singularityIngredient('coal_coke'),
      singularityIngredient('cobalt'),
      singularityIngredient('conductive_alloy'),
      singularityIngredient('constantan'),
      singularityIngredient('copper'),
      singularityIngredient('copper_alloy'),
      singularityIngredient('corrupted'),
      singularityIngredient('crystal_matrix'),
      singularityIngredient('crystallite'),
      singularityIngredient('crystaltine'),
      singularityIngredient('cthonic_gold'),
      singularityIngredient('cupronickel'),
      singularityIngredient('cursium'),
      singularityIngredient('cyanite'),
      singularityIngredient('dark_steel'),
      singularityIngredient('densium'),
      singularityIngredient('depth'),
      singularityIngredient('desh'),
      singularityIngredient('diamond'),
      singularityIngredient('dimensional_shard'),
      singularityIngredient('divine'),
      singularityIngredient('draconium'),
      singularityIngredient('draconium_awakened'),
      singularityIngredient('draculite'),
      singularityIngredient('dragonstone'),
      singularityIngredient('dysprosium'),
      singularityIngredient('eden'),
      singularityIngredient('eden_chunk'),
      singularityIngredient('elecanium'),
      singularityIngredient('electrum'),
      singularityIngredient('elementium'),
      singularityIngredient('emberstone'),
      singularityIngredient('emerald'),
      singularityIngredient('end_steel'),
      singularityIngredient('ender'),
      singularityIngredient('ender_crystal'),
      singularityIngredient('ender_ingot'),
      singularityIngredient('enderite'),
      singularityIngredient('enderium'),
      singularityIngredient('energetic_alloy'),
      singularityIngredient('energized_crystal'),
      singularityIngredient('energized_fluix_crystal'),
      singularityIngredient('energized_superconductive'),
      singularityIngredient('enhanced_ender_ingot'),
      singularityIngredient('enhanced_redstone_ingot'),
      singularityIngredient('enticing_crystal'),
      singularityIngredient('erbium'),
      singularityIngredient('etrium'),
      singularityIngredient('europium'),
      singularityIngredient('extreme'),
      singularityIngredient('ferroboron'),
      singularityIngredient('fiery'),
      singularityIngredient('fire_dragonsteel'),
      singularityIngredient('fluix'),
      singularityIngredient('fluorite'),
    ],
    result: { item: 'kubejs:compressed_singularity_beta' }
  }).id('kubejs:compressed_singularity_beta');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('francium'),
      singularityIngredient('gaia'),
      singularityIngredient('gallium'),
      singularityIngredient('gemenyte'),
      singularityIngredient('ghastly'),
      singularityIngredient('ghost'),
      singularityIngredient('ghoulish'),
      singularityIngredient('gold'),
      singularityIngredient('graphite'),
      singularityIngredient('hafnium'),
      singularityIngredient('hallowed_gold'),
      singularityIngredient('hallowsteel'),
      singularityIngredient('hard_carbon'),
      singularityIngredient('hellstone'),
      singularityIngredient('hepatizon'),
      singularityIngredient('hexium'),
      singularityIngredient('holmium'),
      singularityIngredient('hop_graphite'),
      singularityIngredient('hsla_steel'),
      singularityIngredient('ice'),
      singularityIngredient('ice_dragonsteel'),
      singularityIngredient('ignitium'),
      singularityIngredient('imperium'),
      singularityIngredient('inanite'),
      singularityIngredient('indium'),
      singularityIngredient('inferium'),
      singularityIngredient('infused_iron'),
      singularityIngredient('insanite'),
      singularityIngredient('insanium'),
      singularityIngredient('invar'),
      singularityIngredient('iridium'),
      singularityIngredient('iron'),
      singularityIngredient('ironwood'),
      singularityIngredient('jade'),
      singularityIngredient('jewelyte'),
      singularityIngredient('jungle'),
      singularityIngredient('knightmetal'),
      singularityIngredient('knightslime'),
      singularityIngredient('lacrima'),
      singularityIngredient('lanthanum'),
      singularityIngredient('lapis'),
      singularityIngredient('law'),
      singularityIngredient('lead'),
      singularityIngredient('lead_platinum'),
      singularityIngredient('lightium'),
      singularityIngredient('lightning_dragonsteel'),
      singularityIngredient('lightnum'),
      singularityIngredient('limonite'),
    ],
    result: { item: 'kubejs:compressed_singularity_gamma' }
  }).id('kubejs:compressed_singularity_gamma');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('lithium'),
      singularityIngredient('lithium_manganese_dioxide'),
      singularityIngredient('lucid'),
      singularityIngredient('ludicrite'),
      singularityIngredient('lumium'),
      singularityIngredient('lunar'),
      singularityIngredient('lutetium'),
      singularityIngredient('lyon'),
      singularityIngredient('magentite'),
      singularityIngredient('magnesium'),
      singularityIngredient('magnesium_diboride'),
      singularityIngredient('malachite'),
      singularityIngredient('malignant_lead'),
      singularityIngredient('malignant_pewter'),
      singularityIngredient('mana_diamond'),
      singularityIngredient('manasteel'),
      singularityIngredient('manganese'),
      singularityIngredient('manganese_dioxide'),
      singularityIngredient('manganese_oxide'),
      singularityIngredient('manyullyn'),
      singularityIngredient('molten'),
      singularityIngredient('molybdenum'),
      singularityIngredient('moonstone'),
      singularityIngredient('mortum'),
      singularityIngredient('mortum_chunk'),
      singularityIngredient('mystite'),
      singularityIngredient('neodymium'),
      singularityIngredient('neptunium'),
      singularityIngredient('nether_brick'),
      singularityIngredient('netherite'),
      singularityIngredient('netherite_scrap'),
      singularityIngredient('neutron'),
      singularityIngredient('neutronite'),
      singularityIngredient('neutronium'),
      singularityIngredient('nichrome'),
      singularityIngredient('nickel'),
      singularityIngredient('niobium'),
      singularityIngredient('niobium_tin'),
      singularityIngredient('niobium_titanium'),
      singularityIngredient('niter'),
      singularityIngredient('nutrition_slime'),
      singularityIngredient('olivine'),
      singularityIngredient('onyx'),
      singularityIngredient('opal'),
      singularityIngredient('ornamyte'),
      singularityIngredient('ornium'),
      singularityIngredient('osgloglas'),
      singularityIngredient('osmiridium'),
      singularityIngredient('osmium'),
      singularityIngredient('ostrum'),
      singularityIngredient('ouranium'),
      singularityIngredient('oxdrite'),
      singularityIngredient('palladium'),
      singularityIngredient('pig_iron'),
      singularityIngredient('pink_slime'),
    ],
    result: { item: 'kubejs:compressed_singularity_delta' }
  }).id('kubejs:compressed_singularity_delta');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('platinum'),
      singularityIngredient('plutonium'),
      singularityIngredient('polonium'),
      singularityIngredient('potassium'),
      singularityIngredient('praseodymium'),
      singularityIngredient('prescient_crystal'),
      singularityIngredient('primalite'),
      singularityIngredient('prismarine'),
      singularityIngredient('processed_soulstone'),
      singularityIngredient('prosperity'),
      singularityIngredient('protactinium'),
      singularityIngredient('prudentium'),
      singularityIngredient('pulsating_alloy'),
      singularityIngredient('pulsating_crystal'),
      singularityIngredient('purified_vinteum'),
      singularityIngredient('pyrolitic_carbon'),
      singularityIngredient('quantum_alloy'),
      singularityIngredient('quartz'),
      singularityIngredient('queens_slime'),
      singularityIngredient('quicksilver'),
      singularityIngredient('radium'),
      singularityIngredient('realmite'),
      singularityIngredient('redstone_alloy'),
      singularityIngredient('redstone_ingot'),
      singularityIngredient('refined_glowstone'),
      singularityIngredient('refined_obsidian'),
      singularityIngredient('resonating_ore'),
      singularityIngredient('rhenium'),
      singularityIngredient('rhodium'),
      singularityIngredient('rhodochrosite'),
      singularityIngredient('ridiculite'),
      singularityIngredient('rose_gold'),
      singularityIngredient('rubidium'),
      singularityIngredient('ruby'),
      singularityIngredient('rupee'),
      singularityIngredient('ruthenium'),
      singularityIngredient('rutile'),
      singularityIngredient('salt'),
      singularityIngredient('samarium'),
      singularityIngredient('sapphire'),
      singularityIngredient('scandium'),
      singularityIngredient('scorched_brick'),
      singularityIngredient('seared_brick'),
      singularityIngredient('shadow'),
      singularityIngredient('shibuichi'),
      singularityIngredient('shyregem'),
      singularityIngredient('shyrestone'),
      singularityIngredient('sic_sic_cmc'),
      singularityIngredient('signalum'),
      singularityIngredient('silicon'),
      singularityIngredient('silicon_carbide'),
    ],
    result: { item: 'kubejs:compressed_singularity_epsilon' }
  }).id('kubejs:compressed_singularity_epsilon');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('silver'),
      singularityIngredient('skeletal'),
      singularityIngredient('sky'),
      singularityIngredient('sky_steel'),
      singularityIngredient('skythern'),
      singularityIngredient('skythern_chunk'),
      singularityIngredient('slimesteel'),
      singularityIngredient('sodium'),
      singularityIngredient('soul_stained_steel'),
      singularityIngredient('soularium'),
      singularityIngredient('soulfire'),
      singularityIngredient('soulium'),
      singularityIngredient('soulsteel'),
      singularityIngredient('stainless_steel'),
      singularityIngredient('steel'),
      singularityIngredient('steeleaf'),
      singularityIngredient('stellarium'),
      singularityIngredient('strontium'),
      singularityIngredient('stygian'),
      singularityIngredient('sulfur'),
      singularityIngredient('super_alloy'),
      singularityIngredient('superheated_purified_vinteum'),
      singularityIngredient('superheated_vinteum'),
      singularityIngredient('supremium'),
      singularityIngredient('tainted_gold'),
      singularityIngredient('tantalum'),
      singularityIngredient('terbium'),
      singularityIngredient('terran'),
      singularityIngredient('terrasteel'),
      singularityIngredient('tertium'),
      singularityIngredient('thallium'),
      singularityIngredient('thermoconducting'),
      singularityIngredient('thorium'),
      singularityIngredient('thulium'),
      singularityIngredient('tin'),
      singularityIngredient('tin_silver'),
      singularityIngredient('titanium'),
      singularityIngredient('topaz'),
      singularityIngredient('tornium'),
      singularityIngredient('torridite'),
      singularityIngredient('tough_alloy'),
      singularityIngredient('tungsten'),
      singularityIngredient('tungsten_carbide'),
      singularityIngredient('uranium'),
      singularityIngredient('vanadium'),
      singularityIngredient('varsium'),
      singularityIngredient('vibrant_alloy'),
      singularityIngredient('vibrant_crystal'),
      singularityIngredient('villiaumite'),
      singularityIngredient('vinteum'),
      singularityIngredient('weather_crystal'),
      singularityIngredient('wildwood'),
    ],
    result: { item: 'kubejs:compressed_singularity_zeta' }
  }).id('kubejs:compressed_singularity_zeta');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      singularityIngredient('wildwood_chunk'),
      singularityIngredient('witherite'),
      singularityIngredient('yellorium'),
      singularityIngredient('ytterbium'),
      singularityIngredient('yttrium'),
      singularityIngredient('zanite'),
      singularityIngredient('zinc'),
      singularityIngredient('zircaloy'),
      singularityIngredient('zirconium'),
      singularityIngredient('zirconium_molybdenum'),
    ],
    result: { item: 'kubejs:compressed_singularity_eta' }
  }).id('kubejs:compressed_singularity_eta');

  event.custom({
    type: 'extendedcrafting:shapeless_table',
    tier: 0,
    ingredients: [
      { item: 'kubejs:compressed_singularity_alpha' },
      { item: 'kubejs:compressed_singularity_beta' },
      { item: 'kubejs:compressed_singularity_gamma' },
      { item: 'kubejs:compressed_singularity_delta' },
      { item: 'kubejs:compressed_singularity_epsilon' },
      { item: 'kubejs:compressed_singularity_zeta' },
      { item: 'kubejs:compressed_singularity_eta' },
    ],
    result: { item: 'extendedcrafting:ultimate_singularity' }
  }).id('kubejs:ultimate_singularity_grouped');
});
