// Generated custom ingot part items for KubeJS.
// Existing c:gears, c:plates, c:rods, and c:wires material tags are respected per part type.
// No recipes are added by this script.

const CUSTOM_INGOT_PART_MATERIALS = [
  { id: 'actinium', name: 'Actinium', color: 0x5A95BF, source: 'chemlib:actinium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'adamant', name: 'Adamant', color: 0x496F98, source: 'oritech:adamant_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'adamantium', name: 'Adamantium', color: 0x40A657, source: 'chicken_roost:ingot_adamantium', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'aluminium', name: 'Aluminium', color: 0x929799, source: 'chicken_roost:ingot_aluminum', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ancient_metal', name: 'Ancient Metal', color: 0xA37340, source: 'cataclysm:ancient_metal_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'antimony', name: 'Antimony', color: 0x3F3338, source: 'ftbmaterials:antimony_ingot', parts: ['gear', 'plate', 'rod'] },
  { id: 'aquatic', name: 'Aquatic', color: 0x3C8AC5, source: 'divinerpg:aquatic_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'arlemite', name: 'Arlemite', color: 0x569B3F, source: 'divinerpg:arlemite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'astranite', name: 'Astranite', color: 0xD0AE81, source: 'astral_dimension:astranite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'awakened_supremium', name: 'Awakened Supremium', color: 0xAE650C, source: 'mysticalagriculture:awakened_supremium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'barium', name: 'Barium', color: 0x96BEB2, source: 'chemlib:barium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'baronyte', name: 'Baronyte', color: 0xA74436, source: 'aoa3:baronyte_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'beryllium', name: 'Beryllium', color: 0x4CAD5F, source: 'chemlib:beryllium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'biosteel', name: 'Biosteel', color: 0x5F7F60, source: 'oritech:biosteel_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'bismuth', name: 'Bismuth', color: 0x5EA195, source: 'chemlib:bismuth_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'black_iron', name: 'Black Iron', color: 0x4F4F4F, source: 'extendedcrafting:black_iron_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'black_steel', name: 'Black Steel', color: 0x2B2F39, source: 'cataclysm:black_steel_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'blazium', name: 'Blazium', color: 0xAA663B, source: 'aoa3:blazium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'blutonium', name: 'Blutonium', color: 0x22228A, source: 'bigreactors:blutonium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'cadmium', name: 'Cadmium', color: 0xA85458, source: 'chemlib:cadmium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'calcium', name: 'Calcium', color: 0xA9A296, source: 'chemlib:calcium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'cerium', name: 'Cerium', color: 0x4D5247, source: 'chemlib:cerium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'cesium', name: 'Cesium', color: 0x9CB253, source: 'chemlib:cesium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'chrome', name: 'Chrome', color: 0xCEBDC1, source: 'chicken_roost:ingot_chrome', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'cobalt', name: 'Cobalt', color: 0x4D4DC1, source: 'chemlib:cobalt_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'conductive_alloy', name: 'Conductive Alloy', color: 0xC68F7B, source: 'enderio:conductive_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'corronium', name: 'Corronium', color: 0x209614, source: 'stellaris:corronium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'crystal_matrix', name: 'Crystal Matrix', color: 0x6FAFA3, source: 'avaritia:crystal_matrix_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'crystaltine', name: 'Crystaltine', color: 0x6DBAD9, source: 'extendedcrafting:crystaltine_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'cursium', name: 'Cursium', color: 0x268B75, source: 'cataclysm:cursium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'cyanite', name: 'Cyanite', color: 0x5F93BC, source: 'bigreactors:cyanite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'dark_steel', name: 'Dark Steel', color: 0x4A474C, source: 'enderio:dark_steel_ingot', parts: ['plate', 'rod', 'wire'] },
  { id: 'desh', name: 'Desh', color: 0xC07849, source: 'stellaris:desh_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'draconium', name: 'Draconium', color: 0x5D318B, source: 'draconicevolution:draconium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'draconium_awakened', name: 'Draconium Awakened', color: 0xE0610C, source: 'draconicevolution:awakened_draconium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'dragonsteel_fire', name: 'Dragonsteel Fire', color: 0xB77263, source: 'iceandfire:dragonsteel_fire_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'dragonsteel_ice', name: 'Dragonsteel Ice', color: 0x4A768B, source: 'iceandfire:dragonsteel_ice_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'dragonsteel_lightning', name: 'Dragonsteel Lightning', color: 0x89798D, source: 'iceandfire:dragonsteel_lightning_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'duratium', name: 'Duratium', color: 0x3E324F, source: 'oritech:duratium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'dysprosium', name: 'Dysprosium', color: 0x4C603B, source: 'chemlib:dysprosium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'elecanium', name: 'Elecanium', color: 0x379182, source: 'aoa3:elecanium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'emberstone', name: 'Emberstone', color: 0x975A3F, source: 'aoa3:emberstone_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'end_steel', name: 'End Steel', color: 0xA8AA78, source: 'enderio:end_steel_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ender_ingot', name: 'Ender Ingot', color: 0x0E564A, source: 'extendedcrafting:ender_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'enderite', name: 'Enderite', color: 0x4B1D53, source: 'cataclysm:enderite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'enderium', name: 'Enderium', color: 0x0C5151, source: 'alltheores:enderium_ingot', parts: ['wire'] },
  { id: 'energetic_alloy', name: 'Energetic Alloy', color: 0xD38947, source: 'enderio:energetic_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'energite', name: 'Energite', color: 0xA93FDB, source: 'oritech:energite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'enhanced_ender_ingot', name: 'Enhanced Ender Ingot', color: 0x0C525D, source: 'extendedcrafting:enhanced_ender_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'enhanced_redstone_ingot', name: 'Enhanced Redstone Ingot', color: 0x7A2E0C, source: 'extendedcrafting:enhanced_redstone_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'erbium', name: 'Erbium', color: 0xAC4252, source: 'chemlib:erbium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'europium', name: 'Europium', color: 0x9C95BB, source: 'chemlib:europium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'fiery', name: 'Fiery', color: 0x825222, source: 'twilightforest:fiery_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'firmament_alloy', name: 'Firmament Alloy', color: 0x8F9C9D, source: 'ae2lt:firmament_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'francium', name: 'Francium', color: 0xA83439, source: 'chemlib:francium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'gadolinium', name: 'Gadolinium', color: 0xA14059, source: 'chemlib:gadolinium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'gallium', name: 'Gallium', color: 0xADB295, source: 'chemlib:gallium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'ghastly', name: 'Ghastly', color: 0x709850, source: 'aoa3:ghastly_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ghost', name: 'Ghost', color: 0x498382, source: 'iceandfire:ghost_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ghoulish', name: 'Ghoulish', color: 0x6B6EC5, source: 'aoa3:ghoulish_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'hafnium', name: 'Hafnium', color: 0x4C594E, source: 'chemlib:hafnium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'hallowed_gold', name: 'Hallowed Gold', color: 0xC78A42, source: 'malum:hallowed_gold_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'heavy_metal', name: 'Heavy Metal', color: 0x4C484D, source: 'stellaris:heavy_metal_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'hellstone', name: 'Hellstone', color: 0x623223, source: 'divinerpg:hellstone_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'holmium', name: 'Holmium', color: 0x3A4E41, source: 'chemlib:holmium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'hop_graphite', name: 'Hop Graphite', color: 0x202020, source: 'immersiveengineering:ingot_hop_graphite', parts: ['gear', 'rod', 'wire'] },
  { id: 'ignitium', name: 'Ignitium', color: 0x8A4810, source: 'cataclysm:ignitium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'imperium', name: 'Imperium', color: 0x0C69B2, source: 'mysticalagriculture:imperium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'inanite', name: 'Inanite', color: 0xC71147, source: 'bigreactors:inanite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'indium', name: 'Indium', color: 0x959460, source: 'chemlib:indium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'inferium', name: 'Inferium', color: 0x6E850C, source: 'mysticalagriculture:inferium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'infinity', name: 'Infinity', color: 0xCDC0BD, source: 'avaritia:infinity_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'infused_entro', name: 'Infused Entro', color: 0x2EA385, source: 'extendedae:entro_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'insanite', name: 'Insanite', color: 0x39A880, source: 'bigreactors:insanite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'insanium', name: 'Insanium', color: 0x5D0C90, source: 'mysticalagradditions:insanium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ironwood', name: 'Ironwood', color: 0x655B45, source: 'twilightforest:ironwood_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'knightmetal', name: 'Knightmetal', color: 0x88937A, source: 'twilightforest:knightmetal_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'lanthanum', name: 'Lanthanum', color: 0xC0A14C, source: 'chemlib:lanthanum_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'lightium', name: 'Lightium', color: 0x6A94B2, source: 'mysticalextendedtier:lightium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'limonite', name: 'Limonite', color: 0xB56143, source: 'aoa3:limonite_ingot', parts: ['gear', 'plate', 'wire'] },
  { id: 'lithium', name: 'Lithium', color: 0x9C4C5F, source: 'chemlib:lithium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'lucid', name: 'Lucid', color: 0x5C3C82, source: 'astral_dimension:lucid_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ludicrite', name: 'Ludicrite', color: 0x7829A1, source: 'bigreactors:ludicrite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'lunar', name: 'Lunar', color: 0x944096, source: 'aoa3:lunar_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'lutetium', name: 'Lutetium', color: 0xA13A34, source: 'chemlib:lutetium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'lyon', name: 'Lyon', color: 0x9C7D49, source: 'aoa3:lyon_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'magentite', name: 'Magentite', color: 0xBF35BF, source: 'bigreactors:magentite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'magnesium', name: 'Magnesium', color: 0xB3B3B2, source: 'chemlib:magnesium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'malignant_pewter', name: 'Malignant Pewter', color: 0x815597, source: 'malum:malignant_pewter_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'manganese', name: 'Manganese', color: 0x96AF95, source: 'chemlib:manganese_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'meteorite', name: 'Meteorite', color: 0x66300C, source: 'crystalcraft_unlimited_java:meteorite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'molybdenum', name: 'Molybdenum', color: 0x525FA8, source: 'chemlib:molybdenum_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'mystite', name: 'Mystite', color: 0x609C85, source: 'aoa3:mystite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'nadienite', name: 'Nadienite', color: 0x669819, source: 'ultimatefoods:nadienite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'neodymium', name: 'Neodymium', color: 0x9A5254, source: 'chemlib:neodymium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'neptunium', name: 'Neptunium', color: 0x209E7C, source: 'aquaculture:neptunium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'neutron_star_fragment', name: 'Neutron Star Fragment', color: 0x205994, source: 'ufo:neutron_star_fragment_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'neutronium', name: 'Neutronium', color: 0x494B53, source: 'avaritia:neutron_ingot', parts: ['plate', 'rod', 'wire'] },
  { id: 'niobium', name: 'Niobium', color: 0x5A3A3F, source: 'chemlib:niobium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'ornium', name: 'Ornium', color: 0x4A2B5B, source: 'mysticalextendedtier:ornium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ouranium', name: 'Ouranium', color: 0x325A61, source: 'mysticalextendedtier:ouranium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'oxdrite', name: 'Oxdrite', color: 0x7D5848, source: 'divinerpg:oxdrite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'palladium', name: 'Palladium', color: 0x583445, source: 'chemlib:palladium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'platinium', name: 'Platinium', color: 0x7C909C, source: 'chicken_roost:ingot_platinum', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'polonium', name: 'Polonium', color: 0x523360, source: 'chemlib:polonium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'potassium', name: 'Potassium', color: 0x95A648, source: 'chemlib:potassium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'praseodymium', name: 'Praseodymium', color: 0x5ABF5E, source: 'chemlib:praseodymium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'prometheum', name: 'Prometheum', color: 0x517789, source: 'oritech:prometheum_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'prosperity', name: 'Prosperity', color: 0xA3BFBF, source: 'mysticalagriculture:prosperity_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'protactinium', name: 'Protactinium', color: 0x5F9A4E, source: 'chemlib:protactinium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'prudentium', name: 'Prudentium', color: 0x0C7C15, source: 'mysticalagriculture:prudentium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'pulsar_fragment', name: 'Pulsar Fragment', color: 0x192811, source: 'ufo:pulsar_fragment_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'pulsating_alloy', name: 'Pulsating Alloy', color: 0x5CAC88, source: 'enderio:pulsating_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'radium', name: 'Radium', color: 0x5EA654, source: 'chemlib:radium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'realmite', name: 'Realmite', color: 0xA45F1A, source: 'divinerpg:realmite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'redstone_alloy', name: 'Redstone Alloy', color: 0xB8483B, source: 'enderio:redstone_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'redstone_ingot', name: 'Redstone Ingot', color: 0x7A0C0C, source: 'extendedcrafting:redstone_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'refined_obsidian', name: 'Refined Obsidian', color: 0x2A1E48, source: 'ftbmaterials:refined_obsidian_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'rhenium', name: 'Rhenium', color: 0x484648, source: 'chemlib:rhenium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'rhodium', name: 'Rhodium', color: 0x955852, source: 'chemlib:rhodium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'ridiculite', name: 'Ridiculite', color: 0xAD8AB2, source: 'bigreactors:ridiculite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'rubidium', name: 'Rubidium', color: 0xB49ABF, source: 'chemlib:rubidium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'rupee', name: 'Rupee', color: 0x2B85AF, source: 'divinerpg:rupee_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ruthenium', name: 'Ruthenium', color: 0x58484E, source: 'chemlib:ruthenium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'samarium', name: 'Samarium', color: 0xBBB845, source: 'chemlib:samarium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'scandium', name: 'Scandium', color: 0xBEC14E, source: 'chemlib:scandium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'shyrestone', name: 'Shyrestone', color: 0x5785C3, source: 'aoa3:shyrestone_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'skeletal', name: 'Skeletal', color: 0x887A6E, source: 'aoa3:skeletal_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'sky_bronze', name: 'Sky Bronze', color: 0x764A2D, source: 'megacells:sky_bronze_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'sky_osmium', name: 'Sky Osmium', color: 0x67557A, source: 'megacells:sky_osmium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'sky_steel', name: 'Sky Steel', color: 0x232523, source: 'megacells:sky_steel_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'sodium', name: 'Sodium', color: 0xA39596, source: 'chemlib:sodium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'soul_stained_steel', name: 'Soul Stained Steel', color: 0x9460AE, source: 'malum:soul_stained_steel_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'soularium', name: 'Soularium', color: 0x60513D, source: 'enderio:soularium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'soulium', name: 'Soulium', color: 0x5A3827, source: 'mysticalagriculture:soulium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'steeleaf', name: 'Steeleaf', color: 0x365628, source: 'twilightforest:steeleaf_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'stratus', name: 'Stratus', color: 0xBA8CC2, source: 'deep_aether:stratus_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'strontium', name: 'Strontium', color: 0x4252A6, source: 'chemlib:strontium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'stygian', name: 'Stygian', color: 0x937693, source: 'woot_revived:stygian_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'supremium', name: 'Supremium', color: 0xAE0C0C, source: 'mysticalagriculture:supremium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'tantalum', name: 'Tantalum', color: 0xB2474C, source: 'chemlib:tantalum_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'terbium', name: 'Terbium', color: 0x9CAF3F, source: 'chemlib:terbium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'tertium', name: 'Tertium', color: 0xA7390C, source: 'mysticalagriculture:tertium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'thallium', name: 'Thallium', color: 0x5E3F34, source: 'chemlib:thallium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'tharsite', name: 'Tharsite', color: 0xE7411A, source: 'stellaris:tharsite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'the_ultimate', name: 'The Ultimate', color: 0xC5C5C5, source: 'extendedcrafting:the_ultimate_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'thorium', name: 'Thorium', color: 0x48345A, source: 'chemlib:thorium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'thulium', name: 'Thulium', color: 0x42A836, source: 'chemlib:thulium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'titanum', name: 'Titanum', color: 0xC4C5D0, source: 'chicken_roost:ingot_titanum', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'tornium', name: 'Tornium', color: 0x3B3B3B, source: 'mysticalextendedtier:tornium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'torridite', name: 'Torridite', color: 0xAC2623, source: 'divinerpg:torridite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'tungsten', name: 'Tungsten', color: 0x54585F, source: 'chemlib:tungsten_ingot', parts: ['gear'] },
  { id: 'tungsten_steel', name: 'Tungsten Steel', color: 0x48545D, source: 'chicken_roost:ingot_tungstensteel', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'uranum', name: 'Uranum', color: 0x93C494, source: 'chicken_roost:ingot_uranium', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'vanadium', name: 'Vanadium', color: 0x4C599B, source: 'chemlib:vanadium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'varsium', name: 'Varsium', color: 0x9B5C44, source: 'aoa3:varsium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'vibrant_alloy', name: 'Vibrant Alloy', color: 0xC1D582, source: 'enderio:vibrant_alloy_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'white_dwarf_fragment', name: 'White Dwarf Fragment', color: 0xB8B8B8, source: 'ufo:white_dwarf_fragment_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'witherite', name: 'Witherite', color: 0x6C4B4E, source: 'cataclysm:witherite_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'yellorium', name: 'Yellorium', color: 0x9A9131, source: 'bigreactors:yellorium_ingot', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'ytterbium', name: 'Ytterbium', color: 0xAFAFA9, source: 'chemlib:ytterbium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'yttrium', name: 'Yttrium', color: 0xBB4D94, source: 'chemlib:yttrium_ingot', parts: ['gear', 'rod', 'wire'] },
  { id: 'zinq', name: 'Zinq', color: 0xC8CBC4, source: 'chicken_roost:ingot_zinc', parts: ['gear', 'plate', 'rod', 'wire'] },
  { id: 'zirconium', name: 'Zirconium', color: 0xA3C19C, source: 'chemlib:zirconium_ingot', parts: ['gear', 'rod', 'wire'] },
];

const CUSTOM_INGOT_PART_TYPES = {
  gear: { id: 'gear', name: 'Gear', tag: 'gears' },
  plate: { id: 'plate', name: 'Plate', tag: 'plates' },
  rod: { id: 'rod', name: 'Rod', tag: 'rods' },
  wire: { id: 'wire', name: 'Wire', tag: 'wires' },
};

StartupEvents.registry('item', event => {
  CUSTOM_INGOT_PART_MATERIALS.forEach(material => {
    material.parts.forEach(partId => {
      const part = CUSTOM_INGOT_PART_TYPES[partId];
      event.create(`${material.id}_${part.id}`)
        .displayName(`${material.name} ${part.name}`)
        .color(0, material.color)
        .tag(`c:${part.tag}`)
        .tag(`c:${part.tag}/${material.id}`);
    });
  });
});
